#!/usr/bin/env node

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { createClient } from "@supabase/supabase-js";
import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";
import ws from "ws";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.resolve(__dirname, "../../.env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
  {
    auth: { autoRefreshToken: false, persistSession: false },
    global: { fetch: fetch },
    realtime: {
      transport: ws
    }
  }
);

const server = new Server(
  { name: "deshly-campaign-generator", version: "1.0.0" },
  { capabilities: { tools: {} } }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "list_campaigns",
      description: "List all campaigns generated by Deshly. Returns product, cluster, caption preview, and predicted engagement for each.",
      inputSchema: {
        type: "object",
        properties: {
          limit: { type: "number", description: "Max campaigns to return. Default: 10" },
        },
        required: [],
      },
    },
    {
      name: "get_campaign_detail",
      description: "Get full detail of a specific generated campaign including caption, image prompts, storyboard, hashtags, and predicted outcomes.",
      inputSchema: {
        type: "object",
        properties: {
          campaign_id: { type: "string", description: "UUID of the campaign" },
        },
        required: ["campaign_id"],
      },
    },
    {
      name: "simulate_outcomes",
      description: "Given a cluster_id and brand voice strength score, simulate predicted reach and engagement range for a campaign. Returns confidence-ranged predictions with reasoning.",
      inputSchema: {
        type: "object",
        properties: {
          cluster_id: { type: "string", description: "Target cluster" },
          voice_strength: { type: "number", description: "Brand voice strength 0-1. Default 0.7" },
        },
        required: ["cluster_id"],
      },
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    if (name === "list_campaigns") {
      const limit = args?.limit || 10;
      const { data, error } = await supabase
        .from("campaigns")
        .select("id, cluster_id, product_description, caption, predicted_reach_min, predicted_reach_max, predicted_engagement_min, predicted_engagement_max, created_at")
        .order("created_at", { ascending: false })
        .limit(limit);

      if (error) throw new Error(error.message);
      if (!data.length) return {
        content: [{ type: "text", text: "No campaigns generated yet." }],
      };

      return {
        content: [{
          type: "text",
          text: `# Generated Campaigns (${data.length})\n\n` +
            data.map((c, i) =>
              `## ${i + 1}. ${c.cluster_id}\n` +
              `**Product:** ${c.product_description.substring(0, 80)}...\n` +
              `**Caption preview:** ${c.caption.substring(0, 100)}...\n` +
              `**Reach:** ${c.predicted_reach_min?.toLocaleString()}-${c.predicted_reach_max?.toLocaleString()}\n` +
              `**Engagement:** ${((c.predicted_engagement_min || 0) * 100).toFixed(1)}-${((c.predicted_engagement_max || 0) * 100).toFixed(1)}%\n` +
              `**ID:** \`${c.id}\``
            ).join("\n\n"),
        }],
      };
    }

    if (name === "get_campaign_detail") {
      const { data, error } = await supabase
        .from("campaigns")
        .select("*")
        .eq("id", args.campaign_id)
        .single();

      if (error || !data) throw new Error("Campaign not found");

      return {
        content: [{
          type: "text",
          text: `# Campaign: ${data.cluster_id}\n\n` +
            `## Caption\n${data.caption}\n\n` +
            `## Image Prompts\n**Gemini:** ${data.image_prompts?.gemini}\n\n**Midjourney:** ${data.image_prompts?.midjourney}\n\n**DALL-E:** ${data.image_prompts?.dalle}\n\n` +
            `## Hashtags\n${data.hashtags?.join(" ")}\n\n` +
            `## WhatsApp Message\n${data.whatsapp_message}\n\n` +
            `## Posting Strategy\n${data.posting_time} · ${data.channel_recommendation}\n\n` +
            `## Predicted Outcomes\nReach: ${data.predicted_reach_min?.toLocaleString()}-${data.predicted_reach_max?.toLocaleString()}\nEngagement: ${((data.predicted_engagement_min || 0) * 100).toFixed(1)}-${((data.predicted_engagement_max || 0) * 100).toFixed(1)}%\n\n` +
            `## Reasoning\n${data.reasoning_trace}`,
        }],
      };
    }

    if (name === "simulate_outcomes") {
      const { data, error } = await supabase
        .from("clusters")
        .select("estimated_size, typical_engagement_rate, engagement_std_dev, currency, avg_order_value_min, avg_order_value_max")
        .eq("id", args.cluster_id)
        .single();

      if (error || !data) throw new Error(`Cluster not found: ${args.cluster_id}`);

      const voiceStrength = args.voice_strength || 0.7;
      const strengthMultiplier = 0.7 + (voiceStrength * 0.6);
      const baseEngagement = data.typical_engagement_rate;
      const std = data.engagement_std_dev;

      const engMin = Math.max(0, (baseEngagement - std) * strengthMultiplier);
      const engMax = (baseEngagement + std) * strengthMultiplier;
      const visibilityFactor = 0.08;
      const reachMin = Math.round(data.estimated_size * visibilityFactor * (1 - std * 5));
      const reachMax = Math.round(data.estimated_size * visibilityFactor * (1 + std * 5));

      return {
        content: [{
          type: "text",
          text: `# Outcome Simulation: ${args.cluster_id}\n\n` +
            `## Predicted Reach\n${reachMin.toLocaleString()} – ${reachMax.toLocaleString()} people\n\n` +
            `## Predicted Engagement\n${(engMin * 100).toFixed(1)}% – ${(engMax * 100).toFixed(1)}%\n\n` +
            `## Reasoning\nCluster size: ${data.estimated_size.toLocaleString()}. Organic visibility factor: ${(visibilityFactor * 100).toFixed(0)}% of cluster. ` +
            `Base engagement rate: ${(baseEngagement * 100).toFixed(1)}% ± ${(std * 100).toFixed(1)}% std dev. ` +
            `Brand voice strength multiplier: ${strengthMultiplier.toFixed(2)}x (voice score: ${voiceStrength}). ` +
            `Predictions are ranges — actual performance varies with content quality, posting time accuracy, and platform algorithm changes.\n\n` +
            `*This is a confidence-ranged estimate, not a guarantee.*`,
        }],
      };
    }

    throw new Error(`Unknown tool: ${name}`);
  } catch (err) {
    return {
      content: [{ type: "text", text: `Error: ${err.message}` }],
      isError: true,
    };
  }
});

const transport = new StdioServerTransport();
await server.connect(transport);
console.error("Deshly CampaignGenerator MCP server running on stdio");